export const SIGNUP_START = 'SIGNUP_START';
export const SIGNUP_FAIL = 'SIGNUP_FAIL';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';

export const SIGNIN_START = 'SIGNIN_START';
export const SIGNIN_FAIL = 'SIGNIN_FAIL';
export const SIGNIN_SUCCESS = 'SIGNIN_SUCCESS';

export const LOGIN = 'LOGIN';

export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const ALL_POSTS_SUCCESS = 'ALL_POSTS_SUCCESS';
export const ALL_POSTS_FAIL = 'ALL_POSTS_FAIL';

export const USER_POSTS_SUCCESS = 'USER_POSTS_SUCCESS';
export const USER_POSTS_FAIL = 'USER_POSTS_FAIL';

export const LIKE_POST_SUCCESS = 'LIKE_POST_SUCCESS';
export const LIKE_POST_FAIL = 'LIKE_POST_FAIL';

export const SUBMIT_POST_SUCCESS = 'SUBMIT_POST_SUCCESS';
export const SUBMIT_POST_FAIL = 'SUBMIT_POST_FAIL';

export const COMMENT_SUCCESS = 'COMMENT_SUCCESS';
export const COMMENT_FAIL = 'COMMENT_FAIL';

export const FETCH_COMMENTS_SUCCESS = 'FETCH_COMMENTS_SUCCESS';
export const FETCH_COMMENTS_FAIL = 'FETCH_COMMENTS_FAIL';